package com.xunai.entity;

import java.io.Serializable;
import java.util.Date;

public class ChatRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.send_id
     *
     * @mbggenerated
     */
    private Integer sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.receive_id
     *
     * @mbggenerated
     */
    private Integer receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.id
     *
     * @return the value of chat_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.id
     *
     * @param id the value for chat_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.time
     *
     * @return the value of chat_record.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.time
     *
     * @param time the value for chat_record.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.send_id
     *
     * @return the value of chat_record.send_id
     *
     * @mbggenerated
     */
    public Integer getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.send_id
     *
     * @param sendId the value for chat_record.send_id
     *
     * @mbggenerated
     */
    public void setSendId(Integer sendId) {
        this.sendId = sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.receive_id
     *
     * @return the value of chat_record.receive_id
     *
     * @mbggenerated
     */
    public Integer getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.receive_id
     *
     * @param receiveId the value for chat_record.receive_id
     *
     * @mbggenerated
     */
    public void setReceiveId(Integer receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.content
     *
     * @return the value of chat_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.content
     *
     * @param content the value for chat_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}