package com.xunai.entity;

import java.io.Serializable;

public class UserDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.profile
     *
     * @mbggenerated
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.isVip
     *
     * @mbggenerated
     */
    private Integer isvip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.likes
     *
     * @mbggenerated
     */
    private String likes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.user_id
     *
     * @return the value of user_details.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.user_id
     *
     * @param userId the value for user_details.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.head_img
     *
     * @return the value of user_details.head_img
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.head_img
     *
     * @param headImg the value for user_details.head_img
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.profile
     *
     * @return the value of user_details.profile
     *
     * @mbggenerated
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.profile
     *
     * @param profile the value for user_details.profile
     *
     * @mbggenerated
     */
    public void setProfile(String profile) {
        this.profile = profile == null ? null : profile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.isVip
     *
     * @return the value of user_details.isVip
     *
     * @mbggenerated
     */
    public Integer getIsvip() {
        return isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.isVip
     *
     * @param isvip the value for user_details.isVip
     *
     * @mbggenerated
     */
    public void setIsvip(Integer isvip) {
        this.isvip = isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.likes
     *
     * @return the value of user_details.likes
     *
     * @mbggenerated
     */
    public String getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.likes
     *
     * @param likes the value for user_details.likes
     *
     * @mbggenerated
     */
    public void setLikes(String likes) {
        this.likes = likes == null ? null : likes.trim();
    }
}