package com.xunai.dao;

import com.xunai.entity.ChatRecord;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    int insertSelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    ChatRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatRecord record);
}