package com.xunai.dao;

import com.xunai.entity.UserDetail;

public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    UserDetail selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDetail record);
}